apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: dungx2409/backend:1128cbd7c3c62e02e70a88c420029bd072d9a4c6
          ports:
            - containerPort: 5000