apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: dungx2409/backend:eca6bf801739ff123ebd753a630a427370bfd3af
          ports:
            - containerPort: 5000