apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: dungx2409/backend:a41d7a7d4376ec2264c18f91025dab93403bcbe2
          ports:
            - containerPort: 5000