apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: dungx2409/frontend:a41d7a7d4376ec2264c18f91025dab93403bcbe2
          ports:
            - containerPort: 3000