apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: dungx2409/frontend:eca6bf801739ff123ebd753a630a427370bfd3af
          ports:
            - containerPort: 3000