#!/bin/bash

# ============================================
# TURN Server Setup Script for Ubuntu/Debian
# ============================================
# This script automatically sets up Coturn TURN server with Docker

set -e

echo "============================================"
echo "   WebRTC TURN Server Setup Script"
echo "============================================"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
  echo "❌ Please run as root (use sudo)"
  exit 1
fi

# Get VPS IP
VPS_IP=$(curl -s ifconfig.me)
echo "🌐 Detected VPS IP: $VPS_IP"
echo ""

# Prompt for confirmation
read -p "Is this IP correct? (y/n): " confirm
if [ "$confirm" != "y" ]; then
  read -p "Enter your VPS IP: " VPS_IP
fi

# Prompt for TURN credentials
echo ""
echo "📝 TURN Server Credentials"
echo "   (Leave blank to use defaults)"
read -p "TURN Username [webrtc]: " TURN_USER
TURN_USER=${TURN_USER:-webrtc}

read -sp "TURN Password [webrtc123]: " TURN_PASS
echo ""
TURN_PASS=${TURN_PASS:-webrtc123}

echo ""
echo "============================================"
echo "Starting installation..."
echo "============================================"

# Update system
echo "📦 Updating system..."
apt update -qq
apt upgrade -y -qq

# Install Docker
if ! command -v docker &> /dev/null; then
  echo "🐳 Installing Docker..."
  curl -fsSL https://get.docker.com -o get-docker.sh
  sh get-docker.sh
  rm get-docker.sh
else
  echo "✅ Docker already installed"
fi

# Install Docker Compose
if ! command -v docker-compose &> /dev/null; then
  echo "🐳 Installing Docker Compose..."
  apt install docker-compose -y -qq
else
  echo "✅ Docker Compose already installed"
fi

# Create directory
TURN_DIR="/opt/turn-server"
echo "📁 Creating directory: $TURN_DIR"
mkdir -p $TURN_DIR
cd $TURN_DIR

# Create docker-compose.yml
echo "📄 Creating docker-compose.yml..."
cat > docker-compose.yml <<EOF
version: '3.8'

services:
  turn-server:
    image: coturn/coturn:latest
    container_name: webrtc-turn-server
    network_mode: host
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf
    restart: unless-stopped
EOF

# Create turnserver.conf
echo "📄 Creating turnserver.conf..."
cat > turnserver.conf <<EOF
# TURN Server Configuration
# Generated by setup script

# Listening port for TURN
listening-port=3478

# TLS listening port
tls-listening-port=5349

# Listening IP (0.0.0.0 = all interfaces)
listening-ip=0.0.0.0

# External IP for NAT traversal
external-ip=$VPS_IP

# Relay IP (use same as listening)
relay-ip=$VPS_IP

# Server realm
realm=$VPS_IP

# User credentials (format: username:password)
user=$TURN_USER:$TURN_PASS

# Use fingerprint
fingerprint

# Enable long-term credentials mechanism
lt-cred-mech

# Log file
log-file=/var/log/turnserver.log
verbose

# Disable TCP relay (use UDP only for better performance)
# Comment out to enable TCP relay
no-tcp-relay

# Disable CLI
no-cli

# SSL/TLS certificates (uncomment and configure if using TURNS)
# cert=/etc/letsencrypt/live/turn.yourdomain.com/cert.pem
# pkey=/etc/letsencrypt/live/turn.yourdomain.com/privkey.pem

# Deny access to private IP ranges (security)
no-multicast-peers
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=192.168.0.0-192.168.255.255
denied-peer-ip=172.16.0.0-172.31.255.255

# Quota and rate limiting
max-bps=1000000
bps-capacity=2000000

# Allocate ports range
min-port=49152
max-port=65535
EOF

# Configure firewall
echo "🔒 Configuring firewall..."
if command -v ufw &> /dev/null; then
  ufw --force enable
  ufw allow 22/tcp comment 'SSH'
  ufw allow 3478/tcp comment 'TURN TCP'
  ufw allow 3478/udp comment 'TURN UDP'
  ufw allow 5349/tcp comment 'TURNS TLS'
  ufw allow 49152:65535/udp comment 'TURN Relay Ports'
  echo "✅ UFW firewall configured"
else
  echo "⚠️  UFW not found, please configure firewall manually:"
  echo "   - Allow TCP: 22, 3478, 5349"
  echo "   - Allow UDP: 3478, 49152-65535"
fi

# Start TURN server
echo "🚀 Starting TURN server..."
docker-compose up -d

# Wait for container to start
sleep 3

# Check if container is running
if docker ps | grep -q webrtc-turn-server; then
  echo ""
  echo "============================================"
  echo "   ✅ TURN Server Setup Complete!"
  echo "============================================"
  echo ""
  echo "📊 Server Information:"
  echo "   IP Address: $VPS_IP"
  echo "   TURN Port: 3478 (TCP/UDP)"
  echo "   TURNS Port: 5349 (TLS)"
  echo ""
  echo "🔑 Credentials:"
  echo "   Username: $TURN_USER"
  echo "   Password: $TURN_PASS"
  echo ""
  echo "📝 Configuration saved to: $TURN_DIR"
  echo ""
  echo "🧪 Test your TURN server:"
  echo "   https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/"
  echo ""
  echo "   Use these settings:"
  echo "   - STUN URI: stun:$VPS_IP:3478"
  echo "   - TURN URI: turn:$VPS_IP:3478"
  echo "   - Username: $TURN_USER"
  echo "   - Credential: $TURN_PASS"
  echo ""
  echo "📋 Add to your .env.production:"
  echo "   VITE_TURN_UDP_URL=turn:$VPS_IP:3478?transport=udp"
  echo "   VITE_TURN_TCP_URL=turn:$VPS_IP:3478?transport=tcp"
  echo "   VITE_TURN_TLS_URL=turns:$VPS_IP:5349?transport=tcp"
  echo "   VITE_TURN_USERNAME=$TURN_USER"
  echo "   VITE_TURN_PASSWORD=$TURN_PASS"
  echo ""
  echo "📖 Useful commands:"
  echo "   View logs:      docker logs -f webrtc-turn-server"
  echo "   Restart:        docker-compose restart"
  echo "   Stop:           docker-compose stop"
  echo "   Start:          docker-compose start"
  echo "   Remove:         docker-compose down"
  echo ""
else
  echo ""
  echo "❌ Failed to start TURN server"
  echo "Check logs with: docker logs webrtc-turn-server"
  exit 1
fi

# Show initial logs
echo "📜 Initial logs:"
docker logs webrtc-turn-server 2>&1 | tail -n 20
